app/urls.py
from django.urls import path
from app import views
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('contents/', views.contents, name='contents'),
    path('contact/', views.contact, name='contact'),
    path('contact_form', views.FormView.as_view(), name="contact_form"),
    path('comp/', views.comp, name='comp'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
]

app/models.py
from django.db import models

# Create your models here.


class People(models.Model):
    subject = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    tell = models.CharField(max_length=100)
    sender = models.EmailField(max_length=100)
    message = models.CharField(max_length=500)
    myself = models.BooleanField()

app/forms.py
from django import forms
from .models import People

# フォームクラス作成


class Contact_Form(forms.ModelForm):
    subject = forms.fields.ChoiceField(choices=(("選択してください", "選択してください"), ("アプリケーション作成依頼", "アプリケーション作成依頼"), (
        "アプリケーション使用方法", "アプリケーション使用方法"), ("その他", "その他")), label='お問い合わせ種別', required=True, widget=forms.widgets.Select)
    sender = forms.EmailField(label='メールアドレス', help_text='※ご確認の上、正しく入力してください。')
    message = forms.CharField(label='お問い合わせ内容', widget=forms.Textarea)

    class Meta():
        model = People
        fields = ('subject', 'name', 'tell', 'sender', 'message', 'myself')
        labels = {'subject': "お問い合わせ種別",
                  'name': "名前",
                  'tell': "電話番号",
                  'sender': "メールアドレス",
                  'message': "お問い合わせ内容",
                  'myself': "同じ内容を受け取る",
                  }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = " "


""" from random import choice
from django import forms


class ContactForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = " "

    subject = forms.fields.ChoiceField(choices=(("選択してください", "選択してください"), ("アプリケーション作成依頼", "アプリケーション作成依頼"), (
        "アプリケーション使用方法", "アプリケーション使用方法"), ("その他", "その他")), label='お問い合わせ種別', required=True, widget=forms.widgets.Select)
    name = forms.CharField(label="名前")
    tell = forms.CharField(label="電話番号")
    sender = forms.EmailField(label='メールアドレス', help_text='※ご確認の上、正しく入力してください。')
    message = forms.CharField(label='お問い合わせ内容', widget=forms.Textarea)
    myself = forms.BooleanField(label='同じ内容を受け取る', required=False) """

app/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . import forms
from django.http import HttpResponse
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail


class IndexView(TemplateView):
    template_name = 'index.html'


def index(request):
    return render(request, 'index.html')


def contents(request):
    return render(request, 'contents.html')


def contact(request):
    return render(request, 'contact.html')


""" 送信完了画面"""


def comp(request):
    return render(request, 'comp.html')


class FormView(TemplateView):

    # 初期変数定義
    def __init__(self):
        self.params = {"Message": "情報を入力してください。",
                       "form": forms.Contact_Form(),
                       }

    # GET時の処理を記載
    def get(self, request):
        return render(request, "contact_form.html", context=self.params)

    # POST時の処理を記載
    def post(self, request):
        if request.method == "POST":
            self.params["form"] = forms.Contact_Form(request.POST)

            # フォーム入力が有効な場合
            if self.params["form"].is_valid():
                subject = self.params["form"].cleaned_data['subject']
                name = self.params["form"].cleaned_data['name']
                tell = self.params["form"].cleaned_data['tell']
                message = self.params["form"].cleaned_data['message']
                sender = self.params["form"].cleaned_data['sender']
                myself = self.params["form"].cleaned_data['myself']
                recipients = [settings.EMAIL_HOST_USER]
                bcc = recipients

                message = name + " 様\n\n" + "電話番号：" + tell + "\n\n" + "お問い合わせの内容\n\n" + message

                if myself:
                    recipients.clear()
                    recipients.append(sender)

                try:
                    send_mail(subject, message, sender, recipients, bcc)
                except BadHeaderError:
                    return HttpResponse('無効なヘッダーが見つかりました。')

            # 入力項目をデータベースに保存
            self.params["form"].save(commit=True)
            self.params["Message"] = "入力情報が送信されました。"

            return render(request, "comp.html", context=self.params)


""" お問い合わせフォーム画面"""


""" def contact_form(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)
        form_db = People(request.POST)

        if form.is_valid():
            form_db.save()

            subject = form.cleaned_data['subject']
            name = form.cleaned_data['name']
            tell = form.cleaned_data['tell']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            myself = form.cleaned_data['myself']
            recipients = [settings.EMAIL_HOST_USER]

            message = name + " 様\n\n" + "電話番号：" + tell + "\n\n" + "お問い合わせの内容\n\n" + message

            if myself:
                recipients.append(sender)

            try:
                send_mail(subject, message, sender, recipients)
            except BadHeaderError:
                return HttpResponse('無効なヘッダーが見つかりました。')

            return redirect('comp')

    else:
        form = ContactForm()

    return render(request, 'contact_form.html', {'form': form}) """

app/templates/app/old/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>app</title>
</head>

<body>
    <h1>Hello World!</h1>
</body>

</html>

app/templates/comp.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>Reduce.py</title>
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <meta name="viewport" content="width=device-width. initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://use.fontawesome.com/926fe18a63.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
    <script>
        $(function () {
            $(".headC").click(function () {
                $(".headB").slideToggle();
            });
        });
    </script>
</head>

<style>
    section {
        max-width: 700px;
        max-width: var(--middle-width);
        margin-left: auto;
        margin-right: auto;
        text-align: center;
    }

    .comp_container {
        height: 550px;
    }
</style>

<body class="nohero">
    <header>
        <div class="container">
            <div class="container-small">
                <a href="{% url 'index' %}" class="headA">
                    <img src="{% static 'img/logo.png' %}">
                </a>
                <button type="button" class="headC">
                    <span class="fa fa-bars" title="MENU"></span>
                </button>
            </div>

            <nav class="headB">
                <ul>
                    <li><a href="{% url 'index' %}">Top</a></li>
                    <li><a href="{% url 'contact_form' %}">Contact</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <section>
        <div class="comp_container">
            <br>
            <br>
            <h1>送信完了</h1>
            <p>{{ Message }}</p>
            <p>ご返答までいましばらお待ちください。</p>
            <br>
            <a href=" {% url 'index' %}">
                <p>トップへ</p>
            </a>
        </div>
    </section>

    <footer>
        <div class="container">
            <div class="footA">
                <h2>Reduce.py</h2>
            </div>
            <nav class="footB">
                <div>
                    <ul>
                        <li><a href="{% url 'index' %}">Top</a></li>
                        <li><a href="{% url 'contact' %}">contact</a></li>
                    </ul>
                </div>
            </nav>

            <div class="footC">
                @ 2022 reduce.py All rights reserved.
            </div>
        </div>
    </footer>

</body>

</html>

app/templates/contact_form.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>Reduce.py</title>
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <meta name="viewport" content="width=device-width. initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://use.fontawesome.com/926fe18a63.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
    <script>
        $(function () {
            $(".headC").click(function () {
                $(".headB").slideToggle();
            });
        });
    </script>
</head>

<body class="nohero">
    <header>
        <div class="container">
            <div class="container-small">
                <a href="{% url 'index' %}" class="headA">
                    <img src="{% static 'img/logo.png' %}">
                </a>
                <button type="button" class="headC">
                    <span class="fa fa-bars" title="MENU"></span>
                </button>
            </div>

            <nav class="headB">
                <ul>
                    <li><a href="{% url 'index' %}">Top</a></li>
                    <li><a href="{% url 'contact_form' %}">Contact</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <style>
        section {
            max-width: 700px;
            max-width: var(--middle-width);
            margin-left: auto;
            margin-right: auto;
            padding: 30px 20px 30px;
        }

        h1 {
            padding-left: 0.7rem;
            border-left: solid 0.75rem var(--accent-color);
            font-size: 1.8rem;
            font-family: 'メイリオ';
        }

        p {
            font-size: 1rem;
            line-height: 2;
            font-family: 'メイリオ';
            padding-bottom: 5px;
        }

        /* fieldブロックの上部20px空ける */
        .field {
            margin-top: 20px;
            margin-left: auto;
            margin-right: auto;
            max-width: 800px;
        }

        @media (max-width: 768px) {
            .Form {
                margin-top: 20px;
            }
        }

        /* ブロック要素にする */
        label {
            border-top: 1px solid #ddd;
            padding-top: 5px;
            padding-bottom: 5px;
            max-width: 800px;
            display: flex;
            align-items: center;
        }

        @media (max-width: 768px) {
            label {
                padding-left: 15px;
                padding-right: 15px;
                padding-top: 10px;
                padding-bottom: 0;
                flex-wrap: wrap;
            }
        }

        /* 件名・Emailの枠 */
        input {
            border: 1px solid #ddd;
            border-radius: 6px;
            margin-left: 1px;
            padding-left: 1em;
            padding-right: 1em;
            height: 48px;
            flex: 1;
            width: 92%;
            background: #eaedf2;
            font-size: 18px;
        }

        @media (max-width: 768px) {
            input {
                margin-left: 0;
                margin-top: 5px;
                height: 40px;
                flex: inherit;
                width: 92%;
                font-size: 15px;
            }
        }

        /* 件名・Emailの枠 */
        select {
            border: 1px solid #ddd;
            border-radius: 6px;
            margin-left: 1px;
            padding-left: 1em;
            padding-right: 1em;
            height: 48px;
            flex: 1;
            width: 97%;
            background: #eaedf2;
            font-size: 18px;
        }

        @media (max-width: 768px) {
            select {
                margin-left: 0;
                margin-top: 5px;
                height: 40px;
                flex: inherit;
                width: 97%;
                font-size: 15px;
            }
        }

        /* 注意書きを赤色指定 */
        .helptext {
            color: red;
            font-size: 1rem;
            line-height: 2;
            font-family: 'メイリオ';
            padding-bottom: 0;
            margin-top: 0;
            margin-bottom: 0;
        }

        /* メッセージの枠 */
        textarea {
            border: 1px solid #ddd;
            border-radius: 6px;
            margin-left: 1px;
            padding-left: 1em;
            padding-right: 1em;
            height: 216px;
            flex: 1;
            width: 92%;
            background: #eaedf2;
            font-size: 18px;
        }

        @media (max-width: 768px) {
            textarea {
                margin-top: 18px;
                margin-left: 0;
                height: 200px;
                width: 92%;
                flex: inherit;
                font-size: 15px;
            }
        }

        /* チェックボックス*/
        #id_myself {
            transform: scale(0.5);
            max-width: 48px;

        }

        /* 送信ボタン */
        button[type="submit"] {
            border: none;
            border-radius: 40px;
            margin-top: 60px;
            margin-left: auto;
            margin-right: auto;
            padding-top: 16px;
            padding-bottom: 16px;
            width: 280px;
            display: block;
            letter-spacing: 0.05em;
            background: linear-gradient(#7daff0, #5095f0);
            color: #fff;
            font-weight: bold;
            font-size: 20px;
        }

        button:hover {
            opacity: 0.7;
            cursor: pointer;
        }

        @media (max-width: 768px) {
            button[type="submit"] {
                margin-top: 24px;
                padding-top: 8px;
                padding-bottom: 8px;
                width: 160px;
                font-size: 16px;
            }
        }
    </style>

    <section>

        <h1>Contact -お問い合わせ-</h1>
        <p>アプリケーションの使用方法や作成依頼など、お気軽にご相談ください。</p>
        <br>

        <form action="{% url 'contact_form' %}" method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <div class="field">
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
            <button type="submit">送信</button>
        </form>

    </section>

    <footer>
        <div class="container">
            <div class="footA">
                <h2>Reduce.py</h2>
            </div>
            <nav class="footB">
                <div>
                    <ul>
                        <li><a href="{% url 'index' %}">Top</a></li>
                        <li><a href="{% url 'contact_form' %}">contact</a></li>
                    </ul>
                </div>
            </nav>

            <div class="footC">
                @ 2022 reduce.py All rights reserved.
            </div>
        </div>
    </footer>

</body>

</html>

app/templates/contents.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>Reduce.py</title>
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <meta name="viewport" content="width=device-width. initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://use.fontawesome.com/926fe18a63.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
    <script>
        $(function () {
            $(".headC").click(function () {
                $(".headB").slideToggle();
            });
        });
    </script>
</head>

<body class="nohero">
    <header>
        <div class="container">
            <div class="container-small">
                <a href="{% url 'index' %}" class="headA">
                    <img src="{% static 'img/logo.png' %}">
                </a>
                <button type="button" class="headC">
                    <span class="fa fa-bars" title="MENU"></span>
                </button>
            </div>

            <nav class="headB">
                <ul>
                    <li><a href="{% url 'index' %}">Top</a></li>
                    <li><a href="{% url 'contact_form' %}">Contact</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <article class="post">
        <div class="container">

            <div class="bread">
                <ol>
                    <li><a href="{% url 'index' %}">トップ</a></li>
                    <li><a href="#">アプリケーション一覧</a></li>
                </ol>

                <h1>twitter auto follow</h1>

                <img src="{% static 'img/content_a.png' %}" alt="">

                <p>twitterのフォローを自動で行うツールです。ご自身のトークンを設定してから検索キーワードと繰り返す回数を入力するだけで半永久的にフォローを行います。ツイッター更新担当者様の業務効率を促進します。
                </p>

                <p>twitterのフォローを自動で行うツールです。ご自身のトークンを設定してから検索キーワードと繰り返す回数を入力するだけで半永久的にフォローを行います。ツイッター更新担当者様の業務効率を促進します。
                </p>

                <p>twitterのフォローを自動で行うツールです。ご自身のトークンを設定してから検索キーワードと繰り返す回数を入力するだけで半永久的にフォローを行います。ツイッター更新担当者様の業務効率を促進します。
                </p>

            </div>
    </article>

    <footer>
        <div class="container">
            <div class="footA">
                <h2>Reduce.py</h2>
            </div>
            <nav class="footB">
                <div>
                    <ul>
                        <li><a href="{% url 'index' %}">Top</a></li>
                        <li><a href="{% url 'contact_form' %}">Contact</a></li>
                    </ul>
                </div>
            </nav>

            <div class="footC">
                @ 2022 reduce.py All rights reserved.
            </div>
        </div>
    </footer>

</body>

</html>

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>Reduce.py</title>
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <meta name="viewport" content="width=device-width. initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet">
    <script src="https://use.fontawesome.com/926fe18a63.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
    <script>
        $(function () {
            $(".headC").click(function () {
                $(".headB").slideToggle();
            });
        });
    </script>
</head>

<body>
    <header>
        <div class="container">
            <div class="container-small">
                <a href="{% url 'index' %}" class="headA">
                    <img src="{% static 'img/logo.png' %}">
                </a>
                <button type="button" class="headC">
                    <span class="fa fa-bars" title="MENU"></span>
                </button>
            </div>

            <nav class="headB">
                <ul>
                    <li><a href="{% url 'index' %}">Top</a></li>
                    <li><a href="{% url 'contact_form' %}">Contact</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <section class="conA">
        <div class="container">
            <h1>Tool Collection</h1>
            <p>Do you have a lot of work? We provide tools to reduce the burden</p>
        </div>
    </section>
    <section class="conB">
        <div class="container">
            <div class="image">
                <img src="{% static 'img/content_a.png' %}">
            </div>
            <div class="text">
                <span>2022/02/06</span>
                <h2><a href="{% url 'contents' %}">twitter auto follow</a></h2>
                <p>twitterのフォローを自動で行うツールです。ご自身のトークン
                    を設定してから検索キーワードと繰り返す回数を入力するだけ
                    で半永久的にフォローを行います。ツイッター更新担当者様の
                    業務効率を促進します。</p>
            </div>
        </div>
        <div class="container">
            <div class="image">
                <img src="{% static 'img/content_b.png' %}">
            </div>
            <div class="text">
                <span>2022/02/06</span>
                <h2>twitter auto follow</h2>
                <p>twitterのフォローを自動で行うツールです。ご自身のトークン
                    を設定してから検索キーワードと繰り返す回数を入力するだけ
                    で半永久的にフォローを行います。ツイッター更新担当者様の
                    業務効率を促進します。</p>
            </div>
        </div>
        <div class="container">
            <div class="image">
                <img src="{% static 'img/content_c.jpg' %}">
            </div>
            <div class="text">
                <span>2022/02/06</span>
                <h2>twitter auto follow</h2>
                <p>twitterのフォローを自動で行うツールです。ご自身のトークン
                    を設定してから検索キーワードと繰り返す回数を入力するだけ
                    で半永久的にフォローを行います。ツイッター更新担当者様の
                    業務効率を促進します。</p>
            </div>
        </div>
    </section>
    <footer>
        <div class="container">
            <div class="footA">
                <h2>Reduce.py</h2>
            </div>
            <nav class="footB">
                <div>
                    <ul>
                        <li><a href="{% url 'index' %}">Top</a></li>
                        <li><a href="{% url 'contact_form' %}">Contact</a></li>
                    </ul>
                </div>
            </nav>

            <div class="footC">
                @ 2022 reduce.py All rights reserved.
            </div>
        </div>
    </footer>

</body>

</html>